project_name: yaml-merge
before:
  hooks:
    - go mod tidy
snapshot:
  name_template: "{{ incpatch .Version }}-next"

builds:
  - binary: yaml-merge
    main: ./pkg
    ldflags:
      - -s -w
      - -extldflags
      - -static
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    tags:
      - netgo
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      windows: windows
      linux: linux
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    format: binary
checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  prerelease: auto

dockers:
  - id: yaml-merge
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/nozomi-nishinohara/envoy-container:{{ .Tag }}"
      - "ghcr.io/nozomi-nishinohara/envoy-container:v{{ .Major }}"
      - "ghcr.io/nozomi-nishinohara/envoy-container:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/nozomi-nishinohara/envoy-container:latest"
    dockerfile: Dockerfile
    extra_files:
      - docker-entorypoint.sh
      - envoy.yaml
